### ISSUE TITLE
Not working on Python 3.7.4

### ISSUE THREAD

**Issue by VictorRodriguez** [serge-sans-paille/numpy-benchmarks#12]
Hi I am trying to run the benchmark on python 3.7.4

with the following error: 

~/numpy-benchmarks $ ./np-bench setup
Traceback (most recent call last):
  File "./np-bench", line 544, in <module>
    main()
  File "./np-bench", line 436, in main
    args.func(args)
  File "./np-bench", line 371, in setup
    builder.create(args.venv)
  File "/usr/lib/python3.7/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/usr/lib/python3.7/venv/__init__.py", line 288, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/vrodri3/numpy-benchmarks/.npb/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

~/numpy-benchmarks $ python --version
Python 3.7.4

Any idea why ? 

I also try this with the virtual env, same error

**Comment by serge-sans-paille** [comment]
I'll try to reproduce, thanks for reporting!
